### ISSUE TITLE
doesn't work anymore can you please maintain this repo

### ISSUE THREAD

**Issue by Mootbing** [microsoft/cognitive-services-sdk-react-native-example#23]

**Comment by Mootbing** [comment]
there is some dependency conflicts, which after fixing it is able to be installed on android. However, it crashes when I launch it on android. 

here is the fixed package.json file:
{
  "name": "exampletsproject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "@flyerhq/react-native-android-uri-path": "^2.3.0",
    "@react-native-picker/picker": "^1.12.0",
    "microsoft-cognitiveservices-speech-sdk": "^1.20.0",
    "node-libs-react-native": "^1.2.1",
    "react": "^17.0.1",
    "react-native": "0.66.5",
    "react-native-document-picker": "^5.0.2",
    "react-native-fs": "^2.16.6",
    "react-native-get-random-values": "^1.7.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.20",
    "@types/react-native": "^0.66.16",
    "@types/react-test-renderer": "^17.0.1",
    "babel-jest": "^26.6.3",
    "eslint": "^7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "^17.0.1",
    "typescript": "^3.8.3"
  },
  "resolutions": {
    "@types/react": "^17.0.0",
    "url-parse": "^1.5.7"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}

**Comment by glharper** [comment]
@Mootbing Please take a look at the react-18 branch and see if you can get that running, it works for me.

**Comment by Mootbing** [comment]
omg i am so stupid didnt see that. Can you please put that in the readme lol I spent an entire day tryna diagnose this.

**Comment by Mootbing** [comment]
Ok the react-18 branch works. Thank you so much! On another note, I started a pull request which updates the readme to hint at the existence of the react-18 branch.

I am trying to implement continuous recognition, and I don't know if I am doing it correctly. Here is my code so far (check app.js)
https://github.com/Mootbing/continuous-recognition-react-native

It is giving an error: 
 Error: Error: Browser does not support Web Audio API (AudioContext is not available).

I think this may be some issue because we are sharing the library with the web version and the web has web audio API. How to mitigate this?

**Comment by Mootbing** [comment]
NEVERMIND I FIXED IT IT ACTUALLY WORKS NOW CHECK THE REPO RN AND THE PULL REQUEST I FEEL LIKE A GENIUS RN

**Comment by glharper** [comment]
@Mootbing I really appreciate you getting this working, there have been requests for working mic input since I put this repo up. Would you mind if I pulled in your App.js from your repo as App_mic_input.js, and added a thank you at the end of the readme?

**Comment by Mootbing** [comment]
Sure! Thank you its an honor.

**Comment by Mootbing** [comment]
Also got a translation version working too in the translation branch! 
https://github.com/Mootbing/speech-sdk-continuous-recognition-react-native/tree/translation
if possible add a thank you note to @maxx06 too he helped w. this iteration

**Comment by glharper** [comment]
@Mootbing I've been trying to get this to work on my end...were you able to get actual recognition results? When I run, the recognition session starts and ends properly, but I'm not getting any recognition results.

I'm guessing the cause is a bitrate or format mismatch between the android mic and the formats the speech service accepts (16Khz/16-bit PCM by default).

If you could let me know how you got around this, I'd appreciate it.

**Comment by Mootbing** [comment]
For me it worked on my device (Vivo s7) 
Here is a video (I was using it to simp dw abt what I said)
https://youtube.com/shorts/oq_BIZi_wTQ?feature=share

**Comment by Mootbing** [comment]
Maybe turn on permission for mic in android settings? It didn't ask for some reason and it was failing because of that. OTher than that it worked...

**Comment by Mootbing** [comment]
I got my hands on a Motorola and it is not working. 

I inputted my key and region
I did the permission settings for mic (fsr it didnt prompt)

Ive debugged it little and will work on it more today to try to get it working. Weird it is working on vivo s7 and not a motorola.

**Comment by glharper** [comment]
> I got my hands on a Motorola and it is not working.
> 
> I inputted my key and region I did the permission settings for mic (fsr it didnt prompt)
> 
> Ive debugged it little and will work on it more today to try to get it working. Weird it is working on vivo s7 and not a motorola.

Probably if you can figure out the Motorola issue, you'll give me insight into what's going wrong for my use case. Previous issues like this with JS Speech SDK have tended to be "wrong bitrate," requiring some sort of downsampling to 16KHz, but that hasn't worked for me so far.😞

**Comment by Mootbing** [comment]
It worked without needing to change anything lol since the Motorola I borrowed was from our school robotics team, it had wifi turned off. I just had to connect to the internet 💀💀💀💀💀💀💀💀💀💀💀

**Comment by Mootbing** [comment]
<img width="849" alt="image" src="https://user-images.githubusercontent.com/50122069/228069696-27d34539-a252-4bfc-a74f-5571083bea4c.png">
translations work too

Tell me what you're using... Wierd that it isn't working for you. 

A few rapid fire questions ig:
Do you have developer mode on? should be on to deploy but idk just in case
USB debugging on? idk just in case too
Permissions granted to app? (internet, microphone, and storage fsr even tho I didn't use storage & its not in the androidmanifest.xml)
is the key in?
region typed properly? eastus not useast eg
speechrecog language set right? en-US not us-en etc
Wifi is on? Happened to me...

**Comment by glharper** [comment]
> Tell me what you're using... Wierd that it isn't working for you. 

Android emulator for Pixel 6, API 32 (or 33?)

> Permissions granted to app? (internet, microphone, and storage fsr even tho I didn't use storage & its not in the androidmanifest.xml)

I will add storage and see what happens, but mic permission is already active. 

For the rest, speech service behavior (getting a connection, sessionStarted, recognized event with no text, then sessionStopped) seems to indicate that the service is authenticating properly, but is receiving audio it can't recognize. (Default speech recognition language is "en-US," btw, see [here](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/f37a6d245e1b750dc2571226048e60ec40db520c/src/sdk/SpeechConfig.ts#L404).)

If the audio in from the mic isn't the problem, I'll need to enable debug messages in the SDK using the following line:
`sdk.Diagnostics.SetLoggingLevel(sdk.LogLevel.Debug);` *Warning: this produces a lot of debug output*

Using that, I can at least verify the audio packets are being sent to the service.

I'll add the permissions for storage and internet and give it another go, thanks for confirming this works on actual hardware!

**Comment by glharper** [comment]
Update: Just got it working, mic was turned off in the emulator settings. D'oh!

**Comment by Mootbing** [comment]
Oh lol, it happens to all of us. Idk how to make it prompt for mic access though so maybe some help on that would be appreciated. Also, I was thinking maybe it wouldn't work in emulator like ble-plx or smt but it's good you got it working in emulator.
